server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.133
  rabbitmq:
    virtual-host: /fm
    username: fm
    password: fm
    host: 192.168.82.100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fm:
  jwt:
    pubKeyPath: D:\\FitnessMall\\id_rsa.pub # 公钥地址
    cookieName: FM_TOKEN # cookie的名称