server:
  port: 8083
spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/fitnessmall
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.25.133:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.25.133
    username: fm
    password: fm
    virtual-host: /fm
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fm:
  jwt:
    pubKeyPath: D:\\FitnessMall\\id_rsa.pub # 公钥地址
    cookieName: FM_TOKEN # cookie的名称
#查看SQL语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true