server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #服务拉取时长
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    # 微服务名: 要映射到到地址
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将查询微服务映射到/search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/** # 将上传微服务映射到/upload/**
      serviceId: upload-service
      strip-prefix : false
  sensitive-headers: #设置成没有敏感头信息，默认敏感头有{cookie set-cookie ...}
  add-host-header: true #添加host头信息
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
fm:
  jwt:
    pubKeyPath: D:\\FitnessMall\\id_rsa.pub # 公钥地址
    cookieName: FM_TOKEN # cookie的名称
  filter:
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item
    - /zuul/api/upload/image #上传图片的接口设置为不拦截
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms